# basic options
title: Ed's Learning Blog
author: emuhlestein
email: emuhlestein@yahoo.com
description: This is where I share what I am learning
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - scrum.md
  - javascript.md
  - angular.md
  - about.md
  
# Build settings  
theme: minima
